updated virtualenvwrapper

diff --git a/source/virtualenvwrapper_bashrc b/source/virtualenvwrapper_bashrc
--- a/source/virtualenvwrapper_bashrc
+++ b/source/virtualenvwrapper_bashrc
@@ -60,7 +60,7 @@ export WORKON_HOME
 function virtualenvwrapper_verify_workon_home () {
     if [ ! -d "$WORKON_HOME" ]
     then
-        echo "ERROR: Virtual environments directory '$WORKON_HOME' does not exist." >&2
+        [ "$1" != "-q" ] && echo "ERROR: Virtual environments directory '$WORKON_HOME' does not exist.  Create it or set WORKON_HOME to an existing directory." >&2
         return 1
     fi
     return 0
@@ -90,7 +90,7 @@ EOF
 
 # Set up virtualenvwrapper properly
 function virtualenvwrapper_initialize () {
-    virtualenvwrapper_verify_workon_home || return 1
+    virtualenvwrapper_verify_workon_home -q || return 1
     # mkvirtualenv
     virtualenvwrapper_make_hook "$WORKON_HOME/premkvirtualenv" \
         "This hook is run after a new virtualenv is created and before it is activated."
@@ -316,11 +316,18 @@ if [ -n "$BASH" ] ; then
         # COMPREPLY=( $(compgen -d -- "${VIRTUAL_ENV}/${cur}" | sed -e "s@${VIRTUAL_ENV}/@@" ) )
         COMPREPLY=( $(cdvirtualenv && compgen -d -- "${cur}" ) )
     }
+    _cdsitepackages_complete ()
+    {
+        local cur="$2"
+        COMPREPLY=( $(cdsitepackages && compgen -d -- "${cur}" ) )
+    }
     complete -o nospace -F _cdvirtualenv_complete -S/ cdvirtualenv
+    complete -o nospace -F _cdsitepackages_complete -S/ cdsitepackages
     complete -o default -o nospace -F _virtualenvs workon
     complete -o default -o nospace -F _virtualenvs rmvirtualenv
+    complete -o default -o nospace -F _virtualenvs cpvirtualenv
 elif [ -n "$ZSH_VERSION" ] ; then
-    compctl -g "`virtualenvwrapper_show_workon_options`" workon rmvirtualenv
+    compctl -g "`virtualenvwrapper_show_workon_options`" workon rmvirtualenv cpvirtualenv
 fi
 
 # Prints the Python version string for the current interpreter.
@@ -346,6 +353,7 @@ function virtualenvwrapper_get_site_packages_dir () {
 # created first.
 function add2virtualenv () {
 
+    virtualenvwrapper_verify_workon_home || return 1
     virtualenvwrapper_verify_active_environment || return 1
     
     site_packages="`virtualenvwrapper_get_site_packages_dir`"
@@ -386,13 +394,15 @@ function add2virtualenv () {
 # Does a ``cd`` to the site-packages directory of the currently-active
 # virtualenv.
 function cdsitepackages () {
+    virtualenvwrapper_verify_workon_home || return 1
     virtualenvwrapper_verify_active_environment || return 1
     site_packages="`virtualenvwrapper_get_site_packages_dir`"
-    cd "$site_packages"
+    cd "$site_packages"/$1
 }
 
 # Does a ``cd`` to the root of the currently-active virtualenv.
 function cdvirtualenv () {
+    virtualenvwrapper_verify_workon_home || return 1
     virtualenvwrapper_verify_active_environment || return 1
     cd $VIRTUAL_ENV/$1
 }
@@ -400,6 +410,7 @@ function cdvirtualenv () {
 # Shows the content of the site-packages directory of the currently-active
 # virtualenv
 function lssitepackages () {
+    virtualenvwrapper_verify_workon_home || return 1
     virtualenvwrapper_verify_active_environment || return 1
     site_packages="`virtualenvwrapper_get_site_packages_dir`"
     ls $@ $site_packages
@@ -411,4 +422,49 @@ function lssitepackages () {
         echo "virtualenv_path_extensions.pth:"
         cat "$path_file"
     fi
+}
+
+# Duplicate the named virtualenv to make a new one.
+function cpvirtualenv() {
+
+    typeset env_name="$1"
+    if [ "$env_name" = "" ]
+    then
+        virtualenvwrapper_show_workon_options
+        return 1
+    fi
+    typeset new_env="$2"
+    if [ "$new_env" = "" ]
+    then
+        echo "Please specify target virtualenv"
+        return 1
+    fi
+    if echo "$WORKON_HOME" | grep -e "/$"
+    then
+        env_home="$WORKON_HOME"
+    else
+        env_home="$WORKON_HOME/"
+    fi
+    source_env="$env_home$env_name"
+    target_env="$env_home$new_env"
+    
+    if [ ! -e "$source_env" ]
+    then
+        echo "$env_name virtualenv doesn't exist"
+        return 1
+    fi
+
+    cp -r "$source_env" "$target_env"
+    for script in $( ls $target_env/bin/* )
+      do
+        newscript="$script-new"
+        sed "s|$source_env|$target_env|g" < "$script" > "$newscript"
+        mv "$newscript" "$script"
+        chmod a+x "$script"
+      done
+
+    virtualenv "$target_env" --relocatable
+    sed "s/VIRTUAL_ENV\(.*\)$env_name/VIRTUAL_ENV\1$new_env/g" < "$source_env/bin/activate" > "$target_env/bin/activate"
+    echo "Created $new_env virtualenv"
+    workon "$new_env"
 }
